name: child_safe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_analytics: ^10.2.0

  fl_chart: ^0.61.0
  get_cli: ^1.8.1
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.2.4

  app_usage: ^2.1.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

