// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgVVH8Hhw1VsbI1Mr8z3mluXHXf0S9d34',
    appId: '1:67372471398:web:6c56a059f41eb4d914c9a7',
    messagingSenderId: '67372471398',
    projectId: 'child-safe-3878d',
    authDomain: 'child-safe-3878d.firebaseapp.com',
    storageBucket: 'child-safe-3878d.appspot.com',
    measurementId: 'G-WJR0BQQ1TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9AImiEJaC4j_DghdNqFZRUTe895BKwwk',
    appId: '1:67372471398:android:112b53c750a783c214c9a7',
    messagingSenderId: '67372471398',
    projectId: 'child-safe-3878d',
    storageBucket: 'child-safe-3878d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcyhPfszhxt2-ZpdFrRltZXjLwldqzAO8',
    appId: '1:67372471398:ios:43a577b7dfcc593414c9a7',
    messagingSenderId: '67372471398',
    projectId: 'child-safe-3878d',
    storageBucket: 'child-safe-3878d.appspot.com',
    iosClientId: '67372471398-jbnenmehned5bbhn9iuba63gp8oqsbhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.childSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcyhPfszhxt2-ZpdFrRltZXjLwldqzAO8',
    appId: '1:67372471398:ios:43a577b7dfcc593414c9a7',
    messagingSenderId: '67372471398',
    projectId: 'child-safe-3878d',
    storageBucket: 'child-safe-3878d.appspot.com',
    iosClientId: '67372471398-jbnenmehned5bbhn9iuba63gp8oqsbhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.childSafe',
  );
}
